MODEL:
  architecture: "ConvBiRNN"
  backbone: "ConvGRU"
  shape_pattern: 'NTHWC'
  img_res: 48
  max_seq_len: 16
  num_channels: 14
  num_classes: 20
  dropout: 0.

DATASETS:
  train:
    dataset: 'T31TFM_1618'
    label_map:  'labels_20k2k'
    max_seq_len: 16
    batch_size: 32
    extra_data:
    num_workers: 4  # 10
  eval:
    dataset: 'T31TFM_1618'
    label_map:  'labels_20k2k'
    max_seq_len: 16
    batch_size: 32
    extra_data:
    num_workers: 4  # 10

SOLVER:
  num_epochs: 50
  loss_function: masked_cross_entropy
  class_weights:
  lr_scheduler:
  lr_base: 0.0001
  lr_decay: 0.975
  reset_lr: True   # resets lr to base value when loading pretrained model

CHECKPOINT:
  load_from_checkpoint:
  partial_restore: False
  save_path: "./models/saved_models/France/MTLCC_BiconvGRU"
  train_metrics_steps: 2000
  eval_steps: 4000
  save_steps: 8000
